### ISSUE TITLE
Logging.Demystifier and Diagnostics.Demystifier not working

### ISSUE THREAD

**Issue by zuckerthoben** [twenzel/Demystify.Everything#5]
In a Net Core 2.0 project I am currently trying out the two mentioned packages. Neither of them work for me. 

When I use the logging package, my logs (with nlog, but with net core ILogger in front) dont work anymore. With the diagnostics one I dont get the expected result. I still have the vanilla stack trace.

**Comment by ugumba** [comment]
I see the same thing.  I configure logging in Program.cs:

                .ConfigureLogging((context, builder) =>
                {
                    builder
                        .AddConfiguration(context.Configuration.GetSection("Logging"))
                        .AddConsole()
                        .AddDebug();
                })
                .UseStartup<Startup>()

In Startup:

            services.AddExceptionDemystifyer()

This seems to replace my own logging configuration with a dummy logger provided by Logging.Demystifier.  Nothing appears on the console, and only Information level messages appear in Debug window.

The Diagnostics developer exception page clearly shows a demystified stack trace if you expand the "raw stack trace" at the bottom - so I guess that kind of works.

**Comment by twenzel** [comment]
Thanks for clarification.
Please use the latest version (>= 0.1.27) which fixed this issue. Please have a look at the [readme](https://github.com/twenzel/Demystify.Everything/blob/master/README.md) for usage in Asp.Net Core new style.

**Comment by ugumba** [comment]
Nice, thanks for the fast fix!
